#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Ratemu
#+DATE: <2017-10-23 lun>
#+AUTHOR: Raimon Grau
#+EMAIL: raimonster@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.2 (Org mode 9.0.5)


* What
  Ratemu is an emulator of the shortcuts that ratpoison gives you.
  It's a total hack, written around 2004 that maximizes windows and
  allows you to split windows sizes using just a few shortcuts.

  It's not configurable unless you look at the ugly code and start
  hacking around.

  There's probably lots of dead code in there, but I can't bother to
  check if the script works.  I just found the code in a "googlesites"
  I used to have, and decided to upload it somewhere. Who knows.....

* Who
  Raimon Grau <raimonster@gmail.com>.

* When
  2004

* Where
  Is it really relevant? Ok, Barcelona.


* Why
  In my first job I had to work using windows and I was so used to
  ratpoison shortcuts that I couldn't bare anything that was not
  (ratpoison|screen|vim)-like.

  I knew about autohotkey and autoit that were able to reproduce
  keystrokes programatically, so I wrote a basic 'maximizer', that
  pressed "shift+space+x" to maximize the focused window.

  After a few hours of trance, I had this shit assembled together that
  allows you to split, focus, maximize, move and kill windows.

  Learning about the autoit API I got to make the titles of windows
  disappear, to leave more screen for "WhatMatters(tm)".

* License
  WTFPL
