#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Ratemu
#+DATE: <2017-10-23 lun>
#+AUTHOR: Raimon Grau
#+EMAIL: raimonster@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.2 (Org mode 9.0.5)


* What
  Ratemu is an emulator of the shortcuts that ratpoison gives you.
  It's a total hack, written around 2004 that maximizes windows and
  allows you to split windows sizes using just a few shortcuts.

  It's not configurable unless you look at the ugly code and start
  hacking around.

  There's probably lots of dead code in there, but I can't bother to
  check if the script works.  I just found the code in a "googlepages"
  I used to have, and decided to upload it somewhere. Who knows.....

* Who
  Raimon Grau <raimonster@gmail.com>.

* When
  2004

* Where
  Is it really relevant? Ok, Barcelona.


* Why
  In my first job I had to work using windows and I was so used to
  ratpoison shortcuts that I couldn't bare anything that was not
  (ratpoison|screen|vim)-like.

  I knew about autohotkey and autoit that were able to reproduce
  keystrokes programatically, so I wrote a basic 'maximizer', that
  pressed "shift+space+x" to maximize the focused window.

  After a few hours of trance, I had this shit assembled together that
  allows you to split, focus, maximize, move and kill windows.

  Learning about the autoit API I got to make the titles of windows
  disappear, to leave more screen for "WhatMatters(tm)".

* License
  WTFPL

* Original doc (catalan/spanish)

  Intento de emular el comportamiento de ratpoison en windows... algunas ideas de evilwm

Attempt to emulate ratpoison features in windows env... some evilwm features

"programado" en autoit

ratemu.exe

fuente/font en autoit  :  ratpoison.au3

ara per ara necessita el ejecutor, que és com un Win+r o un slickrun.
c-t + :
    c ->obre terminal
    k -> tanca finestra
    Shift-k-> MATA finestra
    s ->fa un split molt cutre
    v ->vsplit molt cutre
    : ->obre el ejecutor(kogash)
    o ->maximitza i elimina la barra de titol...
    u ->restaura el tamany
    espai -> fa un alt-tab
    y -> "Always on top" a la finestra actual
    b -> treu el "always on top" a la finestra actual
    a -> hora
    c-t -> envia un c-t
    n ->minimitza la finestra actual, deixant la següent finestra al focus.  BUG. Despres de la ultima veiem el fons de pantalla i no sortim d'alla
    - ->Mostra escritori
    ctrl-g -> finalitza ratemu

    q -> posiciona la finestra a la cantonada adalt esquerra (q)
    w -> posiciona la finestra a la cantonada adalt dreta (w)
    z -> posiciona la finestra a la cantonada abaix esquerra (z)
    x -> posiciona la finestra a la cantonada abaix dreta (x)

    comando intermig Idea de evilwm + evilpoison + idea previa
    m -> deixa el tema en un estat de "mou finestra"

        Estat "mou finestra"
         h
         j
         k
         l
        {ENTER}  Acaba el estat "mou finestra"...

      resumint  :                <C-t>m([hjkl])*<CR>              -->mou $1*20pix

   Dllcall es la hostia...

C-t o:

    $handle = WinGetHandle('','');
    $res1 = DllCall("user32.dll","int","GetWindowLong","hwnd",$handle,"int",-16)
    DllCall("user32.dll","int","SetWindowLong","hwnd",$handle,"int",-16,"long",$res1 AND NOT WS_CAPTION)
    WinSetState('','',@SW_MAXIMIZE)
    DllCall("user32.dll","int","ShowWindow","hwnd",$handle,"int",@SW_SHOW)
